server:
  port: 8082

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html